belighted/bosa

- Dockerfile-test
- Jenkinsfile
- ops/release/app/build
- ops/release/assets/build
- modification of build scripts in release , this is due to nexus private registry which needs different logins for different images
- Jenkinsfile added with pipeline , release will be done based on tags like: PROD should have a git tag X.X.X where X is decimal, UAT should have rc-X.X.X where X.X.X is a decimal and any other branches will go directly to dev.
> Ci cd jenkins

- Jenkinsfile
- ops/release/app/Dockerfile
- ops/release/app/build
- ops/release/assets/build
- ops/release/test_runner/Dockerfile
- ops/release/test_runner/build
Fixing intermitent TLS timeout while getting docker image from nexus
> Fix tls docker

- Jenkinsfile
- ops/release/app/Dockerfile
- ops/release/app/build
- ops/release/assets/build
- ops/release/test_runner/Dockerfile
> Migrate nexus

- Jenkinsfile
> Fixing naming in ops folder

- Jenkinsfile
- ops/release/app/Dockerfile
- ops/release/test_runner/Dockerfile
Nexus hotfix 3 - Jenkinsfile fix
> Nexus hotfix 3

- Jenkinsfile
Enriching the deployment to prod with Democracy app update
> Enriching the deployment to prod with Democracy app update

- Gemfile.lock
- db/migrate/20210525110101_add_rrn_hash_to_identities.decidim_verifications_omniauth.rb
- db/schema.rb
See rest of the changes here: https://github.com/belighted/decidim-module-verifications_omniauth/commit/6d11b622fcb1c7c1ba13c591fbb00941dd7c4e9e
> BOSA21Q1-315 Use a hash of national registry number to link CSAM connection to the right user

- config/locales/decidim-core/en.yml
- config/locales/decidim-core/es.yml
- config/locales/decidim-core/fr.yml
- config/locales/decidim-core/nl.yml
- What?
- - Add capital on example
- Why?
- - Can you please add a capital letter in the example so that people understand? 
- How?
- - Just changes in yml files
[BOSA21Q1-173](https://belighted.atlassian.net/browse/BOSA21Q1-173?atlOrigin=eyJpIjoiMDBmZmNmYmUxYjc4NDM1ZDlmZTQ1OWIwOTRkNDA1ZDYiLCJwIjoiaiJ9)
> Bosa & Bosa cities: represent user > add format document (BOSA21Q1-173)

- Gemfile.lock
> Revert mimemagic back to 0.3.5

- Gemfile.lock
PR in module: https://github.com/belighted/decidim-module-verifications_omniauth/pull/10
> Fix metadata read issue in verifications_omniauth module

- Gemfile
- Gemfile.lock
Updated:
We decided to use https://github.com/salsify/goldiloader to fix n+1
problems in the decidim.
Follow up https://github.com/belighted/bosa/pull/84
> BOSA21Q1-246: fix n+1 problems in the app

- public/robots.txt
- What?
- - there is some noise in the error logs because a lot of bots are trying to read files
- Why?
- - bots is not authorised or sometimes wrong path
- How?
- - Add new exceptions in robots.txt file
[BOSA21Q1-230](https://belighted.atlassian.net/browse/BOSA21Q1-230?atlOrigin=eyJpIjoiMTEzNjVkNGE4MmZiNDBiOTg3NTZlODllY2QzNmE4MWQiLCJwIjoiaiJ9)
> BOSA21Q1-230 (TECH) handle gracefully common errors + investigate a legitimate traceback

- Gemfile.lock
- What?
- - Drawing: error in display on result page
- Why?
- - In total, as a result, I got 42 participants & 16 substitutes. So there is an error, it should be written "Participants without substitutes 26"
- How?
- - Update decidim castings gem with the changes i made earlier. 
[BOSA21Q1-200](https://belighted.atlassian.net/browse/BOSA21Q1-200?atlOrigin=eyJpIjoiN2Q0YWQzN2U3YWJiNGRmYzkzNGIwMGY5ODliM2Y5YWQiLCJwIjoiaiJ9)
> BOSA21Q1-200 Drawing: error in display on result page

- Gemfile.lock
Changes in module: https://github.com/belighted/decidim-module-verifications_omniauth/commit/05fd7eacfa857467df7c058e1a4c3732ec9bde75
> BOSA21Q1-359 Fix voting process is lasting too long

- app/views/decidim/initiatives/initiatives/_author.html.erb
- app/views/decidim/initiatives/initiatives/_tags.html.erb
- app/views/decidim/initiatives/initiatives/show.html.erb
Updated:
Added a fragment caching for static fragments related to
current_initiative.
> BOSA21Q1-386: add fragment caching for initiative#show view

- app/views/decidim/account/show.html.erb
- app/views/decidim/devise/registrations/new.html.erb
- config/locales/decidim-core/en.yml
- config/locales/decidim-core/fr.yml
- config/locales/decidim-core/nl.yml
- What?
- - add nickname rules under the field so that user knows what characters are allowed
- Why?
- - More easy to write a good nickname
- How?
- - Add helper on 2 differents views. Registration and account. And also add new key in yml files
[BOSA21Q1-19](https://belighted.atlassian.net/browse/BOSA21Q1-19?atlOrigin=eyJpIjoiMzMyNjVhNjRmZTIyNGIzNzhhYzQ3NmFmZmYzYzM0MDMiLCJwIjoiaiJ9)
> BOSA21Q1-19 nickname rules?

- app/jobs/check_published_suggestions.rb
Related issue:
https://sentry.io/organizations/belighted/issues/2470901239/?project=5471760&query=is%3Aunresolved&statsPeriod=14d
> BOSA21Q1-144 Fix check_published_suggestions job

- app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
Fix gauge to display online and offline signatures when single scope is used
> BOSA21Q1-356 Digital and paper signatures

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/application.rb
- config/initializers/content_security_policy.rb
- config/initializers/devise.rb
- config/routes.rb
- lib/extends/decidim-core/app/presenters/decidim/log/user_presenter.rb
- lib/extends/decidim-core/app/presenters/decidim/user_presenter.rb
Separate PR in bosa-cities app: https://github.com/belighted/bosa-cities/pull/37
> BOSA21Q1-367 Secutiry

- Gemfile.lock
- lib/extends/decidim-suggestions/app/queries/decidim/suggestions/support_period_finished_suggestions.rb
- lib/tasks/decidim_initiatives_extras.rake
Corresponding commit in suggestions module:
https://github.com/belighted/decidim-module-suggestions/commit/5c1fb5a874bc1e5457e1788851b70833b75227fe
> BOSA21Q1-144 Fix sending notification when signature period is over

- Gemfile.lock
- app/views/decidim/homepage/show.html.erb
- app/views/decidim/participatory_processes/admin/participatory_processes/_form.html.erb
- lib/extends/decidim-participatory_processes/app/commands/decidim/participatory_processes/admin/update_participatory_process.rb
Related changes in module: https://github.com/belighted/decidim-module-homepage_interactive_map/commit/341e01f7856ea0767751cbcdb78d38687e185f84
Fixes interactive map with proper extends of logic and minimize overlapping with other modules
> BOSA21Q1-472 BruCity - Add interactive map feature - fix participatory process form

- Gemfile.lock
https://github.com/belighted/decidim-module-homepage_interactive_map/commit/da95ba369609e4565a28dd7506611e86da66cc1f
https://github.com/belighted/decidim-module-homepage_interactive_map/commit/40fa13bfb4babeab4a0ae0c09a3466c112e041c5
> BOSA21Q1-491 Fix participatory process creation

- Gemfile
- Gemfile.lock
The change: https://github.com/belighted/decidim-module-homepage_interactive_map/commit/731499fcde1c1402814ee5d5b7ee24e3362b7608
> BOSA21Q1-491 Fix validating the address of the participatory process

- Gemfile.lock
See PR in module: https://github.com/belighted/decidim-module-verifications_omniauth/pull/13
> BOSA21Q1-647 bosa: performance issue to investigate

- Gemfile.lock
PR in module: https://github.com/belighted/decidim-module-verifications_omniauth/pull/14
> BOSA21Q1-647 Fix generating of nickname

- lib/extends/decidim-initiatives/app/forms/decidim/initiatives/initiative_form.rb
> BOSA21Q1-684 Issue to create petition on La Chambre (prod)

- app/views/decidim/initiatives/initiatives/_progress_bar.html.erb
[BOSA21Q1-731](https://belighted.atlassian.net/browse/BOSA21Q1-731)
To reproduce with prod DB:
- vote ongoing: /initiatives/i-658
- vote closed: /initiatives/i-653
> BOSA21Q1-731 Gauges of votes per region should be visible even after deadline is reached

- public/robots.txt
Part of the changes came from this PR in bosa-cities: https://github.com/belighted/bosa-cities/pull/134
> BOSA21Q1-830, BOSA21Q1-849 Update robots.txt to prevent bots from accessing some pages
