app/views/layouts/decidim/_wrapper.html.erb
Update:
* When there is only Csam as auth option then sign in will redirect to Csam auth page.
=> BOSA21Q1-149: change sign in workflow for csam

Gemfile.lock, app/views/decidim/initiatives/initiatives/_vote_button.html.erb
Updated:
* When the CSAM is only available option to sign in, there is a direct link to CSAM workflow without the modal step.
=> BOSA21Q1-121: change initiative vote behaviour for not signed in user

.gitignore, Gemfile, Gemfile.lock, app/views/decidim/devise/omniauth_registrations/new.html.erb, app/views/layouts/decidim/_wrapper.html.erb, config/locales/de.yml, config/locales/en.yml, config/locales/fr.yml, config/locales/nl.yml, lib/extends/decidim-core/app/helpers/decidim/flash_messages_helper.rb, lib/extends/decidim-core/app/models/decidim/user.rb
Updated:
* disable email confirmation when email is part of the CSAM response
* don't block users to sign in when email is not set
* change omniauth registration form UI
* send email confirmation when email is confirmed
=> BOSA21Q1-122: change workflow for omniauth registration

config/puma.rb
It seems that in production, `Rails` constant is not available at this stage.
=> Fix Puma config

app/views/decidim/initiatives/initiatives/_author.html.erb
- What?
- - Add hyperlink in the initiative show view on the author name like on the index view
- Why?
- - Have the same way of working
- How?
- - Add a balise a with href on the partial author view. I tried with link to but i got an error "undefine method".
[BOSA21Q1-176](https://belighted.atlassian.net/browse/BOSA21Q1-176?atlOrigin=eyJpIjoiZWRlMmM4OTgzZWQ4NDkwMWEzN2ZmOGI3YjQ3ZWE4NTMiLCJwIjoiaiJ9)
=> Petition/suggestion > click on name : BOSA21Q1-176

config/locales/decidim-core/en.yml, config/locales/decidim-core/es.yml, config/locales/decidim-core/fr.yml, config/locales/decidim-core/nl.yml, lib/extends/decidim-core/lib/decidim/authorization_form_builder.rb, lib/extends/decidim-generators/lib/decidim/generators/app_templates/dummy_authorization_handler.rb
- What?
- - Bosa & Bosa cities: represent user > add format document
- Why?
- - The format that is requested now is: any string ending by capital “X”. Can you change the format and make it either “letters or numbers all attached” please? 
- How?
- - Extend the authorization_form_builder and override the all_fields method to add a help text under the document number field. Change locales files. Change the rule for the document number with a regular expression.
[BOSA21Q1-173](https://belighted.atlassian.net/browse/BOSA21Q1-173?atlOrigin=eyJpIjoiNDQyYWMyZDdlMTA5NGM1ZGIwOTNjZmFlNmIyNDZjMzAiLCJwIjoiaiJ9)
=> Bosa & Bosa cities: represent user > add format document BOSA21Q1-173

Gemfile.lock, public/robots.txt
- What?
- - Avoid bots to generate errors in our Appsignal / Sentry errors reports
- Why?
- - Preventing bots from making bad requests
- How?
- - Change robot.txt file to disallow auth path and png extension and other sub folders
[BOSA21Q1-215](https://belighted.atlassian.net/browse/BOSA21Q1-215?atlOrigin=eyJpIjoiOTY1ZTlmOTZlM2Q5NGY2ZmE5ZjFjMzc0ZTQ1ZjcwZDkiLCJwIjoiaiJ9)
=> Avoid bots to generate errors in our Appsignal / Sentry errors reports (BOSA21Q1-215)

Gemfile, Gemfile.lock, app/jobs/sentry_job.rb, config/application.rb
- What?
- - Migrate to the new gem
- Why?
- - The old sentry-raven client has entered maintenance mode. If you're using sentry-raven, we recommend you to migrate to this new SDK.
- How?
- - Change the gemfile with the new library and add dependencies. Change application.rb with the new configuration and remove a job because he is managed by the library.
- Anything Else?
- - I was not able to test locally. So you have to test the code once deployed on staging.
[BOSA21Q1-146](https://belighted.atlassian.net/browse/BOSA21Q1-146?atlOrigin=eyJpIjoiZDU2NmY1N2U2ZWY1NDY3Mjg1Y2M4OGNkYTFlZGU4MjIiLCJwIjoiaiJ9)
=> Migrate Sentry (BOSA21Q1-146)

Gemfile.lock
https://github.com/belighted/decidim-module-verifications_omniauth/commit/3c294333935311a17380a38dc495ac6a2eae38cc
=> BOSA21Q1-315 Use a hash of national registry number to link CSAM connection to the right user - fix access namespace

.gitignore, lib/extends/decidim-initiatives/app/forms/decidim/initiatives/initiative_form.rb
- What?
- - Remove character limitation in title of initiative
- Why?
- - A title can be longer than 150 characters
- How?
- - Extend initiative form. Before clear all validators. After copy/paste validators from the gem and remove the title length. 
[BOSA21Q1-166](ticket_url)
=> Dekamer: remove character limitation in title of initiative (BOSA21Q1-166)

Gemfile.lock, app/views/decidim/initiatives/initiatives/show.html.erb
- What?
- - Let the follow button appear even when not connected
- Why?
- - When I click on it, pop up appears saying "To follow this petition/suggestion, please connect + CSAM button" (just the same as when I click on signing button when I'm not connected)
- How?
- - Remove a condition in the show view which shows the button only when the user is logged in. And update the suggestion module where I made the changes earlier.
[BOSA21Q1-185](https://belighted.atlassian.net/browse/BOSA21Q1-185?atlOrigin=eyJpIjoiN2ZhM2QwMmE4YWU5NGNiZDhhMjNjODU1OGQ3ZTY5NTQiLCJwIjoiaiJ9)
=> BOSA21Q1-185 BOSA: "follow" button of an initiative/suggestion

config/locales/en.yml
- What?
- - Rename BOSA dummy authorization (Direct) to "Admin can impersonate users" in the system
- Why?
- - More understandable
- How?
- - Change en.yml entry
- Anything Else?
- - "(direct)" refers to the name of the strategy, and is found in the identity table, in the provider name attribute
- - !!! Don't forget to push this commit in bosa cities also !!!
[BOSA21Q1-224](https://belighted.atlassian.net/browse/BOSA21Q1-224?atlOrigin=eyJpIjoiMjY4NmRjMWE4NTJiNDM4YzgyOWUwNWMzOWQ3NjNiMDUiLCJwIjoiaiJ9)
=> BOSA21Q1-224 Rename BOSA dummy authorization (Direct) to "Admin can impersonate users" in the system

lib/tasks/users.rake
- What?
- - Delete personal data for exporting production data to other environments
- Why?
- - Security
- How?
- - Run the rake tasks `users:remove_personal_data` on an environment that is not production
https://belighted.atlassian.net/browse/BOSA21Q1-330
=> fake personal data and remove identities & encrypted data

Gemfile.lock, db/migrate/20210601100007_add_decidim_verifications_omniauth_encrypted_metadata_to_authorizations.decidim_verifications_omniauth.rb, db/migrate/20210601100008_allow_null_email_in_decidim_users.decidim_verifications_omniauth.rb, db/schema.rb
BOSA21Q1-320 Verify CSAM data are always saved
Allow nulls in decidim_users.email column
Fix scope mapping might not find the scope
=> BOSA21Q1-320 Verify CSAM data are always saved

Gemfile.lock
The code change is in the module: https://github.com/belighted/decidim-module-verifications_omniauth/commit/39096cafef1f023f027ab9d71fbc4f3ff423c36f
=> BOSA21Q1-320 Fix updating authorization metadata and encryption

Gemfile.lock
**See the code changes in the module**
https://github.com/belighted/decidim-module-cookies/commit/ead9e4349afb6442d106df52643d557615d09c90
**Related tickets**
https://belighted.atlassian.net/browse/BOSA21Q1-335
https://belighted.atlassian.net/browse/BOSA21Q1-334
**Same change/PR for bosa-cities app**
https://github.com/belighted/bosa-cities/pull/20
**What? Why?**
Cookies module was registering itself as a participatory process component, but it doesn't has any logic implemented to support it, and there is no purpose of having it registered as a component at all - there is nothing to do for it.
The change is to remove the registration as a component.
=> BOSA21Q1-335, BOSA21Q1-334 Cookies module shouldn't register itself as a component

app/models/decidim/initiative.rb
- What?
- - This petition doesn't request signatures. But then you see that on the green button it's written "Please identify to sign this initiative". Those 2 are contradictory.
- Why?
- - If you don't have to sign a petition the button should disappear.
- How?
- - Change de method "votes_enabled?" => add the field no_signature in the condition. 
[BOSA21Q1-184](https://belighted.atlassian.net/browse/BOSA21Q1-184?atlOrigin=eyJpIjoiZDEzNWJlY2M0MTkzNGRjNWIyYzJjYmExNjM0OTQwYzEiLCJwIjoiaiJ9)
=> BOSA21Q1-184 De Kamer: signing button of an initiative, different text

lib/extends/decidim-core/app/models/decidim/messaging/message.rb
- What?
- - As a user, when I send a message to another user through the conversation module, I want to be able to send a message without any characters limitation.
- Why?
- - I know the client tried to enter a huge texte (I don’t have the texte anymore) and i did not work.
- How?
- - Extend Message model and remove the body length limitation => (length: { maximum: 1_000 })
[BOSA21Q1-16](https://belighted.atlassian.net/browse/BOSA21Q1-16?atlOrigin=eyJpIjoiMGE0YmIyZjExZWM1NDI3NDlkNDc1ZjE3YTFiZjZjYTQiLCJwIjoiaiJ9)
=> BOSA21Q1-16 Front office: in the conversation module > delete the limitation of characters in a conversation

app/views/decidim/participatory_processes/participatory_processes/show.html.erb
- What?
- - On the presentation page of a process is it possible to delete the blocks below the page which show a preview existing proposals?
- Why?
- - The preview confuses the user (cfr delphine)
- How?
- - Remove highlighted_elements on participatory_process/show view
[BOSA21Q1-170](https://belighted.atlassian.net/browse/BOSA21Q1-170?atlOrigin=eyJpIjoiYTUwZjkwYzA1MjIxNGRhNmEzYmUxNjY1YzcyYTg5NjIiLCJwIjoiaiJ9)
=> BOSA21Q1-170 Bosa & Bosa cities: hide proposals in presentation page of a process

config/environments/development.rb
Updated:
I have disabled the debug option for assets at development, since it
has big performance impact how the app is working. The debug option
should have any influence to preprocessing workflow, but for some
reasons the assets are not properly generated after this change. I
have found that disabling the digest for some cases may solve such a
issue. In our case this combination works fine.
=> BOSA21Q1-246: make tweaks for development assets config

Gemfile.lock
Updated:
I have reverted Bundler and Ruby version to use the same like for
building the app images
=> NT: revert Gemfile.lock changes

Gemfile.lock
- What?
- - Error 500 when person doesn't exist in Person Service
- Why?
- - Answer return by CSAM is nil and the predefined_nickname make an error
- How?
- - Update gemfile.lock to refer of the last version of decidim module verifications_omniauth
[BOSA21Q1-370](https://belighted.atlassian.net/browse/BOSA21Q1-370?atlOrigin=eyJpIjoiYTI5MjdjYWVhOGYyNDllNTlmMWI3ZTVkYTNkNDczZGUiLCJwIjoiaiJ9)
=> BOSA21Q1-370 Issue when person doesn't exist in Person Services (UAT only)

Gemfile.lock
- What?
- - Add hyperlink in the suggestion show view on the author name like on the index view
- Why?
- - Have the same way of working
- How?
- - Update gemfile.lock to refer of the last version of decidim module suggestion
[BOSA21Q1-387](https://belighted.atlassian.net/browse/BOSA21Q1-387?atlOrigin=eyJpIjoiNzYzNDczYTFkYWE0NDBjZjhkYTM3MGE0MDJiYTNmMjEiLCJwIjoiaiJ9)
=> BOSA21Q1-387 On a suggestion page, make the name of the author clickable to see his public profile (as on initiative)

lib/extends/decidim-core/app/controllers/decidim/devise/sessions_controller.rb
- What?
- - Same with this text below, I found the key but the translation doesn’t appear. To arrive on this page, I was connected as an admin in the admin panel, and I simply disconnected.
- Why?
- - Not the good url for logout
- How?
- - Override after_sign_out_path_for in extend to take the good url to logout
!!! Don't forget to push this commit in bosa cities also !!!
[BOSA21Q1-181](https://belighted.atlassian.net/browse/BOSA21Q1-181?atlOrigin=eyJpIjoiOTBmYTUwZGFlMGFlNDRmNzkwYjZhMWFiNDMzYzQxYTgiLCJwIjoiaiJ9)
=> BOSA21Q1-181 BOSA + BOSA cities: add translations

Gemfile, Gemfile.lock, app/assets/javascripts/decidim/translations.js.es6, app/cells/decidim/comments/comment/show.erb, lib/extends/decidim-comments/lib/decidim/comments/comments_helper.rb
Updated:
* Moved back option to translate comments when organization has setup for
deepl API.
* fixed issue with making HTTP call via Net::HTTP. The http_logger gem
used monkey patching which is not properly working for latest rubies.
=> BOSA21Q1-341: recover translation option for comments

app/cells/decidim/progress_bar/show.erb, app/models/decidim/initiative.rb, app/views/decidim/initiatives/admin/initiatives/_form.html.erb, app/views/decidim/initiatives/initiatives/_progress_bar.html.erb, config/locales/decidim-initiatives/en.yml, config/locales/decidim-initiatives/fr.yml, config/locales/decidim-initiatives/nl.yml, lib/extends/decidim-initiatives/app/forms/decidim/initiatives/admin/initiative_form.rb
**What? Why?**
Currently on UI (in front office) we see only online signatures. 
This change adds sub-gauge to display separately the digital signatures and in-person (paper) signatures.
There are also a few fixes to properly handle and update the offline votes count that admin can set for an initiative in admin panel.
**Tickets:**
BOSA21Q1-131 democratie.brussels : signature gauge in several parts
BOSA21Q1-356 democratie.brussels : digital + paper signatures
=> BOSA21Q1-131 & BOSA21Q1-356 democratie.brussels : signature gauge in several parts

Gemfile.lock
**What? Why?**
The user locale is not set when user create his account using CSAM login. It works properly when creating an account using email+pass flow.
**PR in modules:**
https://github.com/belighted/decidim-module-verifications_omniauth/pull/12
=> BOSA21Q1-333 De Kamer: confirmation e-mail in FR instead of NL

.rubocop.yml, Gemfile, Gemfile.lock, app/uploaders/decidim/area_logo_uploader.rb, lib/decidim/core/test/factories.rb, lib/extends/decidim-admin/app/forms/decidim/admin/area_form.rb, lib/extends/decidim-core/app/models/decidim/area.rb, lib/extends/decidim-generators/lib/decidim/generators/app_templates/dummy_authorization_handler.rb, spec/decidim-admin/spec/system/admin_manages_organization_areas_spec.rb, spec/decidim-core/spec/lib/exporters/csv_spec.rb, spec/decidim-core/spec/lib/exporters/excel_spec.rb, spec/decidim-initiatives/spec/forms/admin/initiative_type_form_spec.rb, spec/decidim-initiatives/spec/forms/initiative_form_spec.rb, spec/decidim-initiatives/spec/shared/create_initiative_type_example.rb, spec/decidim-initiatives/spec/shared/update_initiative_type_example.rb, spec/decidim-verifications/spec/services/decidim/dummy_authorization_handler_spec.rb, spec/decidim-verifications/spec/system/authorizations_spec.rb, spec/spec_helper.rb, spec/support/cuprite_setup.rb
Updated:
* fixed broken specs for decidim-admin,  decidim-core, decidim-verifications
* speed up the system tests via cuprite engine
* updated factories
* migrated rubocop setup to latest decidim version
=> BOSA21Q1-96: migrate test suite to 0.24 version

config/initializers/appsignal.rb, config/puma.rb
Updated:
Added appsignal plugin for puma to collect additional stats in our
monitoring utils.
=> BOSA21Q1-408: add appsignal integration for puma

app/assets/stylesheets/decidim/extends/_external-link.scss
Updated:
The list which contains the link with long text is not properly
displayed. This is caused by displaying external-link-container in block
mode in the section or static__content cases. Changing display mode to
inline is fixing this issue. This will fix the case for suggestions, processes, initiatives and static-pages.
=> BOSA21Q1-357: fix displaying list with links

app/views/layouts/decidim/_wrapper.html.erb
Updated:
I have made tweaks for our cache key definition for footer parts to display [reset link](https://github.com/belighted/bosa/blob/master/app/views/layouts/decidim/_main_footer.html.erb#L23) for cookie policy. In the result we can display footer in different states.
=> BOSA21Q1-393: fix issue with displaying links in the footer

ops/release/assets/nginx.conf
Benchmarking the infra (and not the rails app) is interesting so we add
a route only handled by nginx.
=> BOSA21Q1-301: nginx.conf: add a dummy location

ops/release/assets/nginx.conf
On production, /robots.txt triggers an internal error. The reason is
that nginx only serves files in the assets directory, while robots.txt
is directly on the public one. As static file serving is disabled in
production, the files directly in public aren't available.
/public/robots.txt
/public/assets/*
Add a rule to serve static files even if they are from the root
directory. This rule is shamelessly taken from [0]
[0] https://acuments.com/rails-serve-static-files-with-nginx.html
=> BOSA21Q1-230: nginx misconfiguration

ops/release/assets/Dockerfile
This is  a followup of 05e31696e7681bf59a328bdcfe4a04f7b02203f6
Accessing /robots.txt in uat doesn't trigger an internal server error
anymore, but a 404. The expected result was to display the robots.txt
file. By checking the nginx log, we know that this file was actually not
found on the server. By connecting on the server, we saw the only the
file was missing on the server, only the subdirectory "assets" was
found.
It due to how the image is built, where we made available only the
assets directory and not the whole public one.
=> ops: BOSA21Q1-230: bosa-assets doesn't serve the whole public dir

app/models/decidim/initiative.rb, lib/extends/decidim-initiatives/app/commands/decidim/initiatives/admin/update_initiative_answer.rb
Clear answered_at when answer is blank, bring back standard scope for filters
=> BOSA21Q1-418 De Kamer: petition "answered" but shouldn't be

Gemfile.lock
Changes in module: https://github.com/belighted/decidim-module-homepage_interactive_map/commit/7dc5d5c9adc978151bcf5207d9879c599f63a11a
=> BOSA21Q1-505 Interactive map module shouldn't register itself as a component

config/sidekiq.yml
This task is currently ran at 14h.
It uses 20 times the number of postgres transactions than the usual load
during the day. We move this task later in the day so in order to not
impact normal users.
This task was first ran at 17h05 then was changed in [0] for no apparent
nor explained reasons.
[0] 1b134585220a7fcfae7ebfa90e3bfa7fc48e7810
=> BOSA21Q1-507: `CalculateAllMetrics` daily job outside of business hours

app/views/decidim/assemblies/admin/assemblies/_form.html.erb
Without the blank option in the select element there was no option to clear/unlink previously selected participatory processes from an assembly. Blank option allows to remove previously made relations.
=> BOSA21Q1-509 Allow to unlink participatory processes from an assembly

ops/release/assets/nginx.conf
this is the exact same fix as [0] but related to an admin page
[0] 535fab681c2e0892828114e6c01aa4e03ef84e4f
=> BOSA21Q1-217: nginx + admin pages with html escaped characters

ops/release/assets/nginx.conf
previous attempts [0][1] were incomplete because they forgot that urls
like /pages and /admin/static_pages (i.e., without any subpage) should
not go through the disabled unescape thingy but be routed the normal
way. Else, we get an error, because the subgroup is empty.
[0] 535fab681c2e0892828114e6c01aa4e03ef84e4f
[1] abc1940ec4857c1e5e7ca8dc38955b98ec830b21
=> BOSA21Q1-217: nginx + pages and admin pages with html escaped characters

app/assets/stylesheets/decidim/editor.scss, lib/extends/decidim-core/app/scrubbers/decidim/user_input_scrubber.rb
Fix issue displaying OL/UL lists produced by quill editor.
**Problem**: Quill 2.0 stores all lists as OL lists + `data-list` attribute having `ordered` or `bullet` value. We do use html produced by Quill and given all lists are saved as `<ol>` tags they're always displayed as ordered lists even when they were created in editor as bullet lists.
**Reference**: https://github.com/quilljs/quill/issues/3014
**Solution**: To avoid changes via JS for quill (by custom plugin for UL list) the fix is done by CSS only:
- allow `data-list` attribute in Decidim sanitizer
- add custom css to override `list-style-type` for bullet lists
---
Additional minor issue fixed:
```
//@import "quill.snow";
@import "quill-plugins/2.0.0-dev.3-quill.snow.min";
```
Replace quill css from standard quill-1.3 to …
=> BOSA21Q1-561 Fix Quill editor issue displaying all lists as ordered lists

config/initializers/instrumentation.rb
By default, the library doesn't log anything, which isn't convenient.
=> add instrumentation for rack_attack

Gemfile.lock
BOSA21Q1-560 Interactive map fixes:
- change labels of displayed scopes on a map (zones)
- change zone label to display translatable scope title instead of zone name
- fix '_without_dependencies' imports to avoid intersections with decidims `map.js` script
- fix button styles for tooltips displayed for participatory meeting
=> BOSA21Q1-560 Interactive map fixes

lib/extends/decidim-core/app/mailers/decidim/application_mailer.rb
Fixes reply/receiver email on NAPAN and Anderlecht
The only change is a new line added:
`mail.reply_to = @organization.smtp_settings["from_email"].presence || mail.reply_to`
=> BOSA21Q1-634 Set default reply_to based on organization settings

app/jobs/calculate_all_metrics_job.rb, app/jobs/check_published_initiatives.rb, app/jobs/check_published_suggestions.rb, app/jobs/check_validating_initiatives.rb, app/jobs/check_validating_suggestions.rb, app/jobs/clean_sessions.rb, app/jobs/clean_sign_in_ips.rb, app/jobs/notify_progress_initiatives.rb, app/jobs/notify_progress_suggestions.rb, app/jobs/preload_open_data_job.rb
Fix issue with cron jobs when they were executed properly but the code inside (a rake task) wasn't.
Update 'load_tasks' execution to prevent potential multiple initialization of the same rake task.
1. Issue executing rake tasks.
As docs (https://ruby-doc.org/stdlib-2.0.0/libdoc/rake/rdoc/Rake/Task.html#method-i-invoke) says the `invoke` is "Invoke the task if it is needed. Prerequisites are invoked first."
So it only executes the task if it has not already been invoked.
```
> Rake::Task['db:sessions:trim'].invoke
ActiveRecord::SessionStore::Session Destroy (2.8ms)  DELETE FROM "sessions" WHERE (updated_at < '2022-02-14 12:18:33.670409')
=> [#<Proc:0x000055808a04f0a0@/home/sergei-krylov/.rvm/gems/ruby-2.6.6@bosa/gems/activerecord-session_store-2.0.0/lib/tasks/database.rake:15>]
> …
```
=> BOSA21Q1-674 Crons not working

app/views/decidim/accountability/versions/show.html.erb, config/locales/decidim-accountability/en.yml, config/locales/decidim-accountability/fr.yml, config/locales/decidim-accountability/nl.yml
The first part of the review has been done in [this PR](https://github.com/belighted/bosa/pull/204).
We are still waiting for the validation of Bart for the rendering and the translations.
For summary:
- [BOSA21Q1-716](https://belighted.atlassian.net/browse/BOSA21Q1-716) is about all the HTTP 500 detected by AppSignal/Sentry, and may be partially/entirely solved by [BOSA21Q1-719](https://belighted.atlassian.net/browse/BOSA21Q1-719).
- [BOSA21Q1-719](https://belighted.atlassian.net/browse/BOSA21Q1-719) is about configuring robots.txt.
- [BOSA21Q1-721](https://belighted.atlassian.net/browse/BOSA21Q1-721) is for performance issue linked to image comparison.
=> BOSA21Q1-721 Denial of page display in case of image comparison that takes too much server resource

lib/extends/decidim-core/app/controllers/decidim/user_activities_controller.rb, public/robots.txt
[BOSA21Q1-716](https://belighted.atlassian.net/browse/BOSA21Q1-716)
With Sentry and AppSignal we have noticed that bots try to access non existing resources which triggers HTTP 500, which itself triggers an alert in Sentry and AppSignal. These alerts are noise because when using navigation, an end-user can't reach these pages. Still the noise should be removed, those access should return HTTP 404 instead.
=> BOSA21Q1-716 Fix HTTP 500 querying non existing resource

public/robots.txt
Ticket [BOSA21Q1-762](https://belighted.atlassian.net/browse/BOSA21Q1-762)
Solution from [Stackoverflow](https://stackoverflow.com/a/9149936/3790512)
The former line was added following ticket [BOSA21Q1-215](https://belighted.atlassian.net/browse/BOSA21Q1-215) and [this AppSignal incident](https://appsignal.com/belighted/sites/604fdfe25ac13f03e5858fff/exceptions/incidents/175).
Linked to https://github.com/belighted/bosa-cities/pull/104
=> BOSA21Q1-762 robots.txt - add the indexation of /proposals without query param filter

config/initializers/devise.rb
[BOSA21Q1-747](https://belighted.atlassian.net/browse/BOSA21Q1-747)
Actually not relevant for the current config of bosa repository where only csam sign-in is available.
However, if the config changes it could become relevant.
=> BOSA21Q1-747 Fix Devise flash messages translation

lib/extends/decidim-core/app/services/decidim/open_data_exporter.rb, lib/extends/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb
Initially the open data exporter supported only Component type data to be included in open data export (for example Meetings, Comments, Proposals, etc).
The v0.24 introduced the first participatory space to be included into open data - Votings, the PR could be found here: https://github.com/decidim/decidim/pull/7388
After, there was additional enhancement in open data exporter to improve RAM usage and performance: https://github.com/decidim/decidim/pull/8593
This PR brings both open data exporter improvements to v0.22. In our case the Initiatives is the first participatory space that is included in open data.
The `initiatives/participatory_space.rb` contains "tricks" to updates the existing configuration (registration) of the participatory space in Decidim, because it has already been …
=> BOSA21Q1-853 Add initiatives into open data export.

lib/extends/decidim-core/app/services/decidim/open_data_exporter.rb, lib/extends/decidim-initiatives/lib/decidim/initiatives/participatory_space.rb
After "BOSA21Q1-853 Add initiatives into open data export." https://github.com/belighted/bosa/pull/233 the open data export became slower.
To enhance the performance here is a change of how the collection is defined by manifest and handled by exporter.
It is BOSA-specific (not a "PR to decidim" candidate) as default initiatives exporter provided by decidim doesn't include additional data to put into export (see here for extended serializer: https://github.com/belighted/bosa/blob/master/lib/extends/decidim-initiatives/app/serializers/decidim/initiatives/initiative_serializer.rb#L18-L55).
=> BOSA21Q1-861 OpenDataJob performance issue
